### ISSUE TITLE
Move documentation onto GitBooks

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/pasco#264]
Move docs to GitBooks for easy editing and updating

# Tasks
 
- [ ] Create sync between gitbooks and repo
- [ ] Make gitbooks public
- [ ] Update links to docs
- [ ] Add a redirect to new docs
